name: p5.nvim Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release:')"
    steps:
      - name: Checkout automata
        uses: actions/checkout@v4

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.P5NVIM_PUSH_TOKEN }}
          release-type: simple
          target-branch: main
